# Generated by Django 5.1.1 on 2024-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_itemparameters_body_color_itemparameters_car_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='items', verbose_name='Изоброжение'),
        ),
    ]
